### ISSUE TITLE
"creation" was not successfully shared

### ISSUE THREAD

**Issue by z0mbiesrock** [Rosalie241/SporeFixOnline#1] opened 2024-11-12 13:19 UTC
![image](https://github.com/user-attachments/assets/78bf38a5-7ca0-4cf7-8b99-241b1d1e14fd)
It boots me out each time it fails to share too. I think it's server side and might be unable to verify the certificates. It must be reading the old certificates instead of the updated ones.

**Comment by z0mbiesrock** [comment] 2024-11-12 14:22
This happens randomly. Sometimes I can share, but lately it's become even harder and harder to share

**Comment by Rosalie241** [comment] 2024-11-12 15:13
Can you check the console of Spore when that happens? SporeFixOnline will put an error there if certificate validation fails, it can be opened with control + shift + c

**Comment by Rosalie241** [comment] 2024-11-25 22:17
I'm unable to reproduce this issue, so I'll close it, I can re-open it if you provide logs but I doubt it's SporeFixOnline related.

**Closed by Rosalie241** 2024-11-25 22:17 UTC
